Repository tuva-health/medicare_cclf_connector, pull requests merged in 2023-01, with the labels that each got.

#32 changed model materialization
  dbt_project.yml
Labels: bug

#27 Tuva project package refactor
  README.md
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  macros/generate_schema_name.sql
  models/_models.yml
  models/_sources.yml
  models/core/eligibility.sql
  models/core/pharmacy_claim.sql
  models/staging/base_parta_diagnosis_code.sql
  models/staging/base_parta_procedure_code.sql
  models/transformation/diagnosis_pivot.sql
  models/transformation/dme_claims.sql
  models/transformation/institutional_claims.sql
  models/transformation/physician_claims.sql
  models/transformation/procedure_pivot.sql
  packages.yml
  seeds/medicare_state_fips.csv
  seeds/parta_diagnosis_code_seed.csv
  seeds/parta_procedure_code_seed.csv
  seeds/seeds.yml
Labels: enhancement

#33 updated fips_state, readme, and dbt_project.yml
  README.md
  dbt_project.yml
  models/core/eligibility.sql
Labels: bug, enhancement

#37 Fix missing model config
  dbt_project.yml
  docs/catalog.json
  docs/manifest.json
  docs/run_results.json
  models/_models.yml
Labels: bug
